install.packages("rJava")
install.packages("DBI")
install.packages("RJDBC")
install.packages("XML")
install.packages("memoise")
install.packages("KoNLP")
install.packages("wordcloud")
install.packages("dplyr")
install.packages("ggplot2")
install.packages("ggmap")
install.packages("rvest")
install.packages("RColorBrewer")
install.packages("data.table")
install.packages("dplyr")
install.packages("reshape")
install.packages("stringr")
install.packages("tm")


if(!requireNamespace("rJava")){install.packages("rJava")}
if(!requireNamespace("DBI")){install.packages("DBI")}
if(!requireNamespace("RJDBC")){install.packages("RJDBC")}
if(!requireNamespace("XML")){install.packages("XML")}
if(!requireNamespace("memoise")){install.packages("memoise")}
if(!requireNamespace("KoNLP")){install.packages("KoNLP")}
if(!requireNamespace("wordcloud")){install.packages("wordcloud")}
if(!requireNamespace("dplyr")){install.packages("dplyr")}
if(!requireNamespace("ggplot2")){install.packages("ggplot2")}
if(!requireNamespace("ggmap")){install.packages("ggmap")}
if(!requireNamespace("rvest")){install.packages("rvest")}
if(!requireNamespace("RColorBrewer")){install.packages("RColorBrewer")}
if(!requireNamespace("data.table")){install.packages("data.table")}
if(!requireNamespace("dplyr")){install.packages("dplyr")}
if(!requireNamespace("reshape")){install.packages("reshape")}
if(!requireNamespace("shiny")){install.packages("shiny")}
if(!requireNamespace("shinyjs")){install.packages("shinyjs")}
if(!requireNamespace("shinydashboard")){install.packages("shinydashboard")}